@startuml
' Custom AWS Icons
!define AWSIcon(name) rectangle "<img:https://icons.terrastruct.com/aws/\name.svg>" as name
!define S3Icon() AWSIcon(Storage/Amazon-Simple-Storage-Service-S3)
!define SQSIcon() AWSIcon(Application-Integration/Amazon-Simple-Queue-Service-SQS)
!define LambdaIcon() AWSIcon(Compute/AWS-Lambda)
!define ECRIcon() AWSIcon(Containers/Amazon-Elastic-Container-Registry)

' Resources
S3Icon() s3
SQSIcon() sqs
LambdaIcon() lambda_inbox
LambdaIcon() lambda_outbox
ECRIcon() ecr

rectangle "S3 Bucket\n(Existing)" as s3_label
rectangle "SQS Queue" as sqs_label
rectangle "Lambda (inbox)" as lambda_inbox_label
rectangle "Lambda (outbox)" as lambda_outbox_label
rectangle "ECR Repository" as ecr_label

s3 -[hidden]-> s3_label
sqs -[hidden]-> sqs_label
lambda_inbox -[hidden]-> lambda_inbox_label
lambda_outbox -[hidden]-> lambda_outbox_label
ecr -[hidden]-> ecr_label

' Custom components
component "Docker Image" as docker_image
component "Custom Lambda Layer" as custom_layer
component "S3 Bucket Notification" as s3_notification
component "SQS Queue Policy" as sqs_policy
component "Lambda Event Source Mapping" as event_mapping
component "IAM Role Policies" as iam_policies

' Relationships
s3 --> s3_notification
s3_notification --> sqs
sqs --> sqs_policy
sqs --> event_mapping
event_mapping --> lambda_inbox
ecr --> docker_image
docker_image --> lambda_inbox
custom_layer --> lambda_outbox
iam_policies --> lambda_inbox
iam_policies --> lambda_outbox

@enduml
